// output/react/src/blocks/button.jsx
import * as React from "react";

function Button(props) {
  return (
    <>
      {props.link ? (
        <>
          <a
            role="button"
            {...props.attributes}
            href={props.link}
            target={props.openLinkInNewTab ? "_blank" : undefined}
          >
            {props.text}
          </a>
        </>
      ) : (
        <span {...props.attributes}>{props.text}</span>
      )}
    </>
  );
}

export default Button;

// output/vue/vue3/src/blocks/button.vue
<template>
  <template v-if="link">
    <a
      role="button"
      :href="link"
      :target="openLinkInNewTab ? '_blank' : undefined"
      v-bind="attributes"
    >
      {{ text }}
    </a>
  </template>

  <template v-else>
    <span v-bind="attributes">{{ text }}</span>
  </template>
</template>

<script>
export default {
  name: "button",

  props: ["attributes", "text", "link", "openLinkInNewTab"],
};
</script>
