// output/qwik/src/blocks/button.jsx
import { Fragment, component$, h } from "@builder.io/qwik";

export const Button = component$((props) => {
  return (
    <Fragment>
      {props.link ? (
        <a
          role="button"
          {...props.attributes}
          href={props.link}
          target={props.openLinkInNewTab ? "_blank" : undefined}
        >
          {props.text}
        </a>
      ) : (
        <span {...props.attributes}>{props.text}</span>
      )}
    </Fragment>
  );
});

export default Button;

// output/react/src/blocks/button.jsx
import * as React from "react";

function Button(props) {
  return (
    <>
      {props.link ? (
        <>
          <a
            role="button"
            {...props.attributes}
            href={props.link}
            target={props.openLinkInNewTab ? "_blank" : undefined}
          >
            {props.text}
          </a>
        </>
      ) : (
        <span {...props.attributes}>{props.text}</span>
      )}
    </>
  );
}

export default Button;
